<?php
namespace MMAF\DataEngine\Migrations;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class Schema {
	public static function table_names(): array {
		global $wpdb;

		return array(
			'fighters'             => $wpdb->prefix . 'mmaf_fighters',
			'fighter_sources'      => $wpdb->prefix . 'mmaf_fighter_sources',
			'fighter_aliases'      => $wpdb->prefix . 'mmaf_fighter_aliases',
			'events'               => $wpdb->prefix . 'mmaf_events',
			'event_sources'        => $wpdb->prefix . 'mmaf_event_sources',
			'bouts'                => $wpdb->prefix . 'mmaf_bouts',
			'bout_sources'         => $wpdb->prefix . 'mmaf_bout_sources',
			'bout_participants'    => $wpdb->prefix . 'mmaf_bout_participants',
			'field_provenance'     => $wpdb->prefix . 'mmaf_field_provenance',
			'fighter_stats_current'=> $wpdb->prefix . 'mmaf_fighter_stats_current',
			'fighter_stats_overrides'=> $wpdb->prefix . 'mmaf_fighter_stats_overrides',
			'ranking_runs'         => $wpdb->prefix . 'mmaf_ranking_runs',
			'ranking_current'      => $wpdb->prefix . 'mmaf_ranking_current',
			'ranking_snapshots'    => $wpdb->prefix . 'mmaf_ranking_snapshots',
			'source_import_runs'   => $wpdb->prefix . 'mmaf_source_import_runs',
			'source_import_items'  => $wpdb->prefix . 'mmaf_source_import_items',
			'review_items'         => $wpdb->prefix . 'mmaf_review_items',
			'audit_log'            => $wpdb->prefix . 'mmaf_audit_log',
			'system_state'         => $wpdb->prefix . 'mmaf_system_state',
		);
	}

	public static function sql(): array {
		global $wpdb;

		$tables          = self::table_names();
		$charset_collate = $wpdb->get_charset_collate();

		return array(
			"CREATE TABLE {$tables['fighters']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				wp_post_id BIGINT UNSIGNED NULL,
				display_name VARCHAR(255) NOT NULL,
				nickname VARCHAR(255) NULL,
				normalized_name VARCHAR(255) NULL,
				gender VARCHAR(20) NULL,
				date_of_birth DATE NULL,
				birth_year SMALLINT UNSIGNED NULL,
				nationality VARCHAR(100) NULL,
				weight_class VARCHAR(80) NULL,
				height VARCHAR(60) NULL,
				height_cm SMALLINT UNSIGNED NULL,
				last_weigh_in VARCHAR(60) NULL,
				status VARCHAR(40) NOT NULL DEFAULT 'provisional',
				rankability_status VARCHAR(80) NOT NULL DEFAULT 'pending_review',
				is_public TINYINT(1) NOT NULL DEFAULT 0,
				is_rankable TINYINT(1) NOT NULL DEFAULT 0,
				in_ufc TINYINT(1) NOT NULL DEFAULT 0,
				deleted_soft TINYINT(1) NOT NULL DEFAULT 0,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY wp_post_id (wp_post_id),
				KEY normalized_name (normalized_name),
				KEY status (status),
				KEY rankability_status (rankability_status),
				KEY is_rankable (is_rankable),
				KEY in_ufc (in_ufc)
			) $charset_collate;",
			"CREATE TABLE {$tables['fighter_sources']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				fighter_id BIGINT UNSIGNED NULL,
				source_type VARCHAR(50) NOT NULL,
				source_fighter_id VARCHAR(120) NULL,
				source_numeric_id VARCHAR(80) NULL,
				source_url TEXT NULL,
				source_slug VARCHAR(255) NULL,
				identity_hash CHAR(64) NULL,
				confidence TINYINT UNSIGNED NULL,
				is_verified TINYINT(1) NOT NULL DEFAULT 0,
				is_primary TINYINT(1) NOT NULL DEFAULT 0,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY fighter_id (fighter_id),
				KEY source_type (source_type),
				KEY source_fighter_id (source_fighter_id),
				KEY identity_hash (identity_hash),
				KEY source_identity (source_type, source_fighter_id)
			) $charset_collate;",
			"CREATE TABLE {$tables['fighter_aliases']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				fighter_id BIGINT UNSIGNED NOT NULL,
				alias VARCHAR(255) NOT NULL,
				normalized_alias VARCHAR(255) NULL,
				source_type VARCHAR(50) NULL,
				is_verified TINYINT(1) NOT NULL DEFAULT 0,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY fighter_id (fighter_id),
				KEY normalized_alias (normalized_alias),
				KEY is_verified (is_verified)
			) $charset_collate;",
			"CREATE TABLE {$tables['events']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				event_name VARCHAR(255) NOT NULL,
				normalized_event_name VARCHAR(255) NULL,
				event_date DATE NULL,
				event_datetime_utc DATETIME NULL,
				timezone_raw VARCHAR(100) NULL,
				promotion_name VARCHAR(255) NULL,
				venue VARCHAR(255) NULL,
				location VARCHAR(255) NULL,
				city VARCHAR(120) NULL,
				country VARCHAR(120) NULL,
				region VARCHAR(120) NULL,
				status VARCHAR(40) NOT NULL DEFAULT 'valid',
				deleted_soft TINYINT(1) NOT NULL DEFAULT 0,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY event_date (event_date),
				KEY normalized_event_name (normalized_event_name),
				KEY promotion_name (promotion_name),
				KEY status (status),
				KEY deleted_soft (deleted_soft)
			) $charset_collate;",
			"CREATE TABLE {$tables['event_sources']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				event_id BIGINT UNSIGNED NULL,
				source_type VARCHAR(50) NOT NULL,
				source_event_id VARCHAR(120) NOT NULL,
				source_event_numeric_id VARCHAR(80) NULL,
				source_promotion_id VARCHAR(120) NULL,
				source_promotion_numeric_id VARCHAR(80) NULL,
				source_promotion_url TEXT NULL,
				source_url TEXT NULL,
				source_slug VARCHAR(255) NULL,
				identity_hash CHAR(64) NOT NULL,
				content_hash CHAR(64) NULL,
				raw_payload LONGTEXT NULL,
				last_import_run_id BIGINT UNSIGNED NULL,
				is_verified TINYINT(1) NOT NULL DEFAULT 0,
				is_primary TINYINT(1) NOT NULL DEFAULT 0,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY event_id (event_id),
				KEY source_type (source_type),
				KEY source_event_id (source_event_id),
				KEY identity_hash (identity_hash),
				KEY content_hash (content_hash),
				KEY source_identity (source_type, source_event_id)
			) $charset_collate;",
			"CREATE TABLE {$tables['bouts']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				event_id BIGINT UNSIGNED NOT NULL,
				bout_order INT NULL,
				card_position VARCHAR(80) NULL,
				weight_class VARCHAR(80) NULL,
				weight_lbs SMALLINT UNSIGNED NULL,
				status VARCHAR(80) NOT NULL DEFAULT 'valid',
				result_type VARCHAR(40) NULL,
				method_category VARCHAR(60) NULL,
				method_detail VARCHAR(255) NULL,
				round_number TINYINT UNSIGNED NULL,
				time_in_round VARCHAR(20) NULL,
				is_scoring_candidate TINYINT(1) NOT NULL DEFAULT 0,
				deleted_soft TINYINT(1) NOT NULL DEFAULT 0,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY event_id (event_id),
				KEY status (status),
				KEY result_type (result_type),
				KEY is_scoring_candidate (is_scoring_candidate),
				KEY deleted_soft (deleted_soft)
			) $charset_collate;",
			"CREATE TABLE {$tables['bout_sources']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				bout_id BIGINT UNSIGNED NULL,
				event_source_id BIGINT UNSIGNED NULL,
				source_type VARCHAR(50) NOT NULL,
				source_bout_id VARCHAR(120) NOT NULL,
				source_bout_numeric_id VARCHAR(80) NULL,
				source_url TEXT NULL,
				identity_hash CHAR(64) NOT NULL,
				content_hash CHAR(64) NULL,
				raw_payload LONGTEXT NULL,
				last_import_run_id BIGINT UNSIGNED NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY bout_id (bout_id),
				KEY event_source_id (event_source_id),
				KEY source_type (source_type),
				KEY source_bout_id (source_bout_id),
				KEY identity_hash (identity_hash),
				KEY content_hash (content_hash),
				KEY source_identity (source_type, source_bout_id)
			) $charset_collate;",
			"CREATE TABLE {$tables['bout_participants']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				bout_id BIGINT UNSIGNED NOT NULL,
				fighter_id BIGINT UNSIGNED NULL,
				participant_role VARCHAR(20) NOT NULL,
				source_fighter_id VARCHAR(120) NULL,
				source_fighter_numeric_id VARCHAR(80) NULL,
				source_name VARCHAR(255) NULL,
				result_for_fighter VARCHAR(40) NULL,
				opponent_fighter_id BIGINT UNSIGNED NULL,
				prefight_wins INT NULL,
				prefight_losses INT NULL,
				prefight_draws INT NULL,
				prefight_nc INT NULL,
				prefight_record_raw VARCHAR(80) NULL,
				opponent_prefight_wins INT NULL,
				opponent_prefight_losses INT NULL,
				opponent_prefight_draws INT NULL,
				opponent_prefight_nc INT NULL,
				opponent_prefight_record_raw VARCHAR(80) NULL,
				opponent_prefight_diff INT NULL,
				is_winner TINYINT(1) NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY bout_id (bout_id),
				KEY fighter_id (fighter_id),
				KEY source_fighter_id (source_fighter_id),
				KEY result_for_fighter (result_for_fighter),
				KEY participant_role (participant_role)
			) $charset_collate;",
			"CREATE TABLE {$tables['field_provenance']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				entity_type VARCHAR(80) NOT NULL,
				entity_id BIGINT UNSIGNED NOT NULL,
				field_name VARCHAR(120) NOT NULL,
				source_type VARCHAR(50) NOT NULL,
				source_id VARCHAR(120) NULL,
				value_hash CHAR(64) NULL,
				locked TINYINT(1) NOT NULL DEFAULT 0,
				verified_by BIGINT UNSIGNED NULL,
				verified_at DATETIME NULL,
				first_seen_at DATETIME NULL,
				last_seen_at DATETIME NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY entity_lookup (entity_type, entity_id),
				KEY field_name (field_name),
				KEY source_type (source_type),
				KEY locked (locked)
			) $charset_collate;",
			"CREATE TABLE {$tables['fighter_stats_current']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				fighter_id BIGINT UNSIGNED NOT NULL,
				wins INT NOT NULL DEFAULT 0,
				losses INT NOT NULL DEFAULT 0,
				draws INT NOT NULL DEFAULT 0,
				nc INT NOT NULL DEFAULT 0,
				pro_fights_count INT NOT NULL DEFAULT 0,
				ko_tko_wins INT NOT NULL DEFAULT 0,
				submission_wins INT NOT NULL DEFAULT 0,
				decision_wins INT NOT NULL DEFAULT 0,
				finish_wins INT NOT NULL DEFAULT 0,
				finish_rate DECIMAL(6,3) NULL,
				last_fight_date DATE NULL,
				streak VARCHAR(40) NULL,
				recent_form VARCHAR(80) NULL,
				activity_status VARCHAR(80) NULL,
				warnings_json LONGTEXT NULL,
				calculated_at DATETIME NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY fighter_id (fighter_id),
				KEY last_fight_date (last_fight_date),
				KEY activity_status (activity_status)
			) $charset_collate;",
			"CREATE TABLE {$tables['fighter_stats_overrides']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				fighter_id BIGINT UNSIGNED NOT NULL,
				wins INT NOT NULL DEFAULT 0,
				losses INT NOT NULL DEFAULT 0,
				draws INT NOT NULL DEFAULT 0,
				nc INT NOT NULL DEFAULT 0,
				display_record_raw VARCHAR(80) NOT NULL,
				reason TEXT NULL,
				calculated_stats_hash CHAR(64) NULL,
				is_active TINYINT(1) NOT NULL DEFAULT 1,
				created_by BIGINT UNSIGNED NULL,
				updated_by BIGINT UNSIGNED NULL,
				cleared_by BIGINT UNSIGNED NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				cleared_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY fighter_id (fighter_id),
				KEY is_active (is_active)
			) $charset_collate;",
			"CREATE TABLE {$tables['ranking_runs']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				formula_version VARCHAR(40) NOT NULL,
				formula_config_snapshot LONGTEXT NOT NULL,
				reference_date DATE NOT NULL,
				calculated_at DATETIME NOT NULL,
				status VARCHAR(40) NOT NULL DEFAULT 'draft',
				is_active TINYINT(1) NOT NULL DEFAULT 0,
				notes TEXT NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY formula_version (formula_version),
				KEY reference_date (reference_date),
				KEY status (status),
				KEY is_active (is_active)
			) $charset_collate;",
			"CREATE TABLE {$tables['ranking_current']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				ranking_run_id BIGINT UNSIGNED NOT NULL,
				board_key VARCHAR(80) NOT NULL,
				fighter_id BIGINT UNSIGNED NOT NULL,
				rank_position INT NOT NULL,
				total_score DECIMAL(10,3) NOT NULL,
				raw_score DECIMAL(10,3) NULL,
				normalized_score DECIMAL(10,3) NULL,
				confidence_score DECIMAL(6,3) NULL,
				sample_size INT NOT NULL DEFAULT 0,
				quality_flags_json LONGTEXT NULL,
				breakdown_json LONGTEXT NULL,
				eligibility_json LONGTEXT NULL,
				warnings_json LONGTEXT NULL,
				source_summary_json LONGTEXT NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY ranking_run_id (ranking_run_id),
				KEY board_key (board_key),
				KEY fighter_id (fighter_id),
				KEY normalized_score (normalized_score),
				KEY confidence_score (confidence_score),
				UNIQUE KEY board_fighter (board_key, fighter_id)
			) $charset_collate;",
			"CREATE TABLE {$tables['ranking_snapshots']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				ranking_run_id BIGINT UNSIGNED NOT NULL,
				board_key VARCHAR(80) NOT NULL,
				fighter_id BIGINT UNSIGNED NOT NULL,
				rank_position INT NOT NULL,
				total_score DECIMAL(10,3) NOT NULL,
				raw_score DECIMAL(10,3) NULL,
				normalized_score DECIMAL(10,3) NULL,
				confidence_score DECIMAL(6,3) NULL,
				sample_size INT NOT NULL DEFAULT 0,
				quality_flags_json LONGTEXT NULL,
				previous_rank_position INT NULL,
				previous_total_score DECIMAL(10,3) NULL,
				movement INT NULL,
				breakdown_json LONGTEXT NULL,
				eligibility_json LONGTEXT NULL,
				warnings_json LONGTEXT NULL,
				source_summary_json LONGTEXT NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY ranking_run_id (ranking_run_id),
				KEY board_key (board_key),
				KEY fighter_id (fighter_id),
				KEY normalized_score (normalized_score),
				KEY confidence_score (confidence_score)
			) $charset_collate;",
			"CREATE TABLE {$tables['source_import_runs']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				source_type VARCHAR(50) NOT NULL,
				source_schema_version VARCHAR(80) NULL,
				source_run_id VARCHAR(120) NULL,
				payload_hash CHAR(64) NOT NULL,
				status VARCHAR(60) NOT NULL DEFAULT 'pending',
				mode VARCHAR(40) NULL,
				dry_run TINYINT(1) NOT NULL DEFAULT 0,
				started_at DATETIME NULL,
				finished_at DATETIME NULL,
				summary_json LONGTEXT NULL,
				error_message TEXT NULL,
				created_by BIGINT UNSIGNED NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY source_type (source_type),
				KEY source_schema_version (source_schema_version),
				KEY source_run_id (source_run_id),
				KEY payload_hash (payload_hash),
				KEY status (status)
			) $charset_collate;",
			"CREATE TABLE {$tables['source_import_items']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				import_run_id BIGINT UNSIGNED NOT NULL,
				item_type VARCHAR(50) NOT NULL,
				source_id VARCHAR(120) NULL,
				identity_hash CHAR(64) NULL,
				content_hash CHAR(64) NULL,
				canonical_id BIGINT UNSIGNED NULL,
				status VARCHAR(60) NOT NULL,
				action VARCHAR(60) NULL,
				warnings_json LONGTEXT NULL,
				error_message TEXT NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				KEY import_run_id (import_run_id),
				KEY item_type (item_type),
				KEY source_id (source_id),
				KEY identity_hash (identity_hash),
				KEY content_hash (content_hash),
				KEY status (status)
			) $charset_collate;",
			"CREATE TABLE {$tables['review_items']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				item_type VARCHAR(80) NOT NULL,
				item_key VARCHAR(191) NOT NULL,
				source_type VARCHAR(50) NULL,
				source_id VARCHAR(120) NULL,
				canonical_id BIGINT UNSIGNED NULL,
				related_canonical_id BIGINT UNSIGNED NULL,
				status VARCHAR(40) NOT NULL DEFAULT 'open',
				action_taken VARCHAR(120) NULL,
				notes TEXT NULL,
				created_by BIGINT UNSIGNED NULL,
				resolved_by BIGINT UNSIGNED NULL,
				resolved_at DATETIME NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY item_key (item_key),
				KEY item_type (item_type),
				KEY source_lookup (source_type, source_id),
				KEY canonical_id (canonical_id),
				KEY related_canonical_id (related_canonical_id),
				KEY status (status)
			) $charset_collate;",
			"CREATE TABLE {$tables['audit_log']} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				actor_user_id BIGINT UNSIGNED NULL,
				action VARCHAR(120) NOT NULL,
				entity_type VARCHAR(80) NULL,
				entity_id BIGINT UNSIGNED NULL,
				before_json LONGTEXT NULL,
				after_json LONGTEXT NULL,
				reason TEXT NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY  (id),
				KEY actor_user_id (actor_user_id),
				KEY action (action),
				KEY entity_lookup (entity_type, entity_id),
				KEY created_at (created_at)
			) $charset_collate;",
			"CREATE TABLE {$tables['system_state']} (
				state_key VARCHAR(120) NOT NULL,
				state_value LONGTEXT NULL,
				autoload VARCHAR(20) NOT NULL DEFAULT 'no',
				updated_at DATETIME NULL,
				PRIMARY KEY  (state_key)
			) $charset_collate;",
		);
	}
}
